# The aim of this R code is to automatically create to compare the diagnositc ability between two subgroups
# We compare the true and false predictions generated by logistic regression between the two subgroups using the 
# Fisher exact test. 

# @Input: data
# @Input: SampleGroup: a dataframe, one column is sampleID, one column is Group;
# @Input: Selected.Genes
# @Input: table.name
# @Input: CpGsite2Gene_method: which specifies the transformation method. 
# @Output: A Table

library(pROC)
Subgroup_Compare = function(data, SampleGroup, Selected.Genes, output_name, CpGsite2Gene_method){

  data = subset(data, Gene %in% Selected.Genes)
  new.data = CpGsite2Gene_method(data)
  data = new.data[[1]]
  data = as.data.frame(t(na.omit(t(data))),stringsAsFactors = F)
  data[,-c(1:3)] = apply(data[,-c(1:3)], 2, function(x) as.numeric(as.character(x)))
  
  Type = sapply(colnames(data)[-c(1:3)], function(x){ return(substr(x,1,1)) })
  Type = ifelse(Type == "N", 0, 1)
  data_table = as.data.frame(t(data[,-c(1:3)]))
  colnames(data_table) = data$Gene
  methydata = data.frame(Type, data_table)
  
  #Logistic regression analysis
  Gene = c()
  Type = c()
  Correct = c()
  Incorrect = c()
  Pvalue = c()
  
    for(i in 1:(dim(methydata)[2] -1 )){
      for(j in unique(SampleGroup$Group)){
        SampleID = sapply(rownames(methydata), function(x) strsplit(x, "[.]")[[1]][2])
        tmp.data = methydata[which(SampleID %in% SampleGroup$SampleID[SampleGroup$Group == j]), ]
        
        temp = tmp.data[,c(1,i+1 )]
        temp[,1] = as.factor(temp[,1])
        glm.fit  = glm(temp[,1] ~ temp[,2], data = temp, family = "binomial") 
        
        logistic.rocobj  = roc(tmp.data[,1], as.vector(t(predict(glm.fit))),smooth = FALSE)
        logistic.rocdata = data.frame(Sens = logistic.rocobj$sensitivities, Spec = logistic.rocobj$specificities)
        logistic.rocdata$Combine = logistic.rocdata[,1] + logistic.rocdata[,2]
        seq.bestcutoff = which( logistic.rocdata$Combine == max(logistic.rocdata$Combine))[1]
        bestcutoff = logistic.rocobj$thresholds[seq.bestcutoff]
        predType = cut(as.vector(t(predict(glm.fit))), breaks =c(-Inf, bestcutoff, Inf), labels=c(0,1))
        cTab = table(tmp.data[,1], predType, dnn=c("actual", "predicted"))
        Type = append(Type, j)
        Correct = append(Correct, cTab[1,1] + cTab[2,2])
        Incorrect = append(Incorrect, cTab[1,2] + cTab[2,1])
      }
      Gene = append(Gene, c(colnames(methydata)[i+1], colnames(methydata)[i+1]))
      P = fisher.test(data.frame(c(Correct[2*i -1], Incorrect[2*i -1]), c(Correct[2*i], Incorrect[2*i])))$p.value
      Pvalue = append(Pvalue, c(format(P, digits = 4), format(P, digits = 4)))
    }
    output = data.frame(Gene, Type, Correct, Incorrect, Pvalue)
  write.csv(output, file = paste(output_name, "csv", sep="."), row.names=FALSE)
}
